name: Validate

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: dcodeIO/setup-node-nvm@master
    - run: npm install
    - run: npm run bootstrap

  lint_code:
    name: Lint Code
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: dcodeIO/setup-node-nvm@master
    - run: npm run lint:no-fail

  unit_test:
    name: Unit Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: dcodeIO/setup-node-nvm@master
    - run: npm test

